// AVG_PROC.C
#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include "stdlib.h"
/* run locally on 'server' called by a remote client. */
static char sum_avg;

/* 
 *  * routine notice the _1 the version number 
 *   * notice the client handle, not sued here but needs to be 
 *    * a parameter 
 *     */
input_data * average_1(input_data *input, CLIENT *client) 
  {
  printf("starting avergae_1");
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  char *dp = input->input_data.input_data_val;
  printf(dp);
  return( input );
}

/* 
 *  * server stub 'average_1_svc function handle called in avg_svc that was
 *   * generated by rpcgen 
 *    * FYI:
 *     *   result = (*local)((char *)&argument, rqstp);
 *      *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 *       */
 
input_data *average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
