// RAVG.C
#include "avg.h"	/* header file generated by rpcgen */ 
#include <stdlib.h>


/* local routine client */
/* prototype can be whatever you want */
void averageprog_1( char* host, int argc, char *argv[] )
{
   CLIENT *clnt; /* client handle, rpc.h included in avg.h from rpcgen */
   int i;
   char *aChar , *endptr, *dp, *test, *word;
   input_data  average_1_arg, *result_1; /* input_data rpc struct */

   // 200 character limit
   average_1_arg.input_data.input_data_val = (char*) malloc(MAXAVGSIZE*sizeof(char));
   /* pointer to CHAR, beginning of input data */
   dp = average_1_arg.input_data.input_data_val;
    
   /* set number of items  OR DOES THIS NOW SET IT TO A STRING?*/
   //average_1_arg.input_data.input_data_len = argc - 2;
   
   word = argv[argc-1];
   printf("%s\n", word);
   //average_1_arg.input_data.input_data_val = dp;
   average_1_arg.input_data.input_data_len = sizeof(argv[2]);

   for( i = 1; i <= (argc - 2); i++ )
   {
	/* str to d ASCII string to floating point nubmer */
 	test = argv[argc-1];
	
	printf("argv[argc-1] = %s\n", word);
        printf("value   = %s\n", test);
        *dp = *test;
        dp = dp + sizeof(test);
   }
   printf("%s SHOULD BE BUBBLES\n" , test);
   //printf(average_1_arg.input_data.input_data_len);
   // For the third argument, do like in the first program and just write it?
   //for( i = 1; i <= (argc - 2); i++  )
   //{
	/* str to d ASCII string to floating point nubmer */
 	//SO WE ARE FINE WITH STR STAYING STR HERE
	//f = strtod( argv[i+1], &endptr);
        
        //printf("value   = %c\n", i);
        //*dp = i;
        //dp++;
   //}


   /*  clnt_create(host, program, version, protocol)
 *      * generic client create routine from rpc library * * program = AVERAGEPROG is the number 22855 
 *          * version = AVERAGEVERS is 1
 *              * transfer protocol 
 *                  *
 *                      * defined by application programmer in avg.x and  then
 *                          * these definitions in turn are generated into avg.h 
 *                              * udp is of-course the user datagram protocol 
 *                                  *
 *                                      * returns a client RPC handle
 *                                          */

   clnt = clnt_create( host, AVERAGEPROG, AVERAGEVERS, "udp" );
   
   /* check if error */
   if (clnt == NULL) 
   {
    
  /* 
 *        * rpc error library routine
 *               *  print a more descriptive error 
 *                      */
   
      clnt_pcreateerror( host );
      exit(1);
   }


   /* now call average routine 'just' like a local routine 
 *     * but this will now go over network 
 *         * average_1 is definined in the client stub 
 *             * avg_clnt.c  that was generated by rpcgen
 *                 * send in ptr to the parameters or args  in first field, and 
 *                     * client handle in second field (created in clnt_create ) 
 *                         * average_1 ultimately calls clnt_call() macro see man rpc
 *                             *  than calls the remote routine associated with the client handle
 *                                 * so AVERAGEPROG, VERSION 
 *                                     */
   printf(test);
   printf("\nAbout to send the above to average_1\n");
   printf("%s\n", &average_1_arg);
   *result_1 = average_1_arg; 
   result_1 = average_1( &average_1_arg, clnt );

   printf("post result_1\n");
   dp = result_1->input_data.input_data_val;
   printf("Word returned is %s\n",*dp);
   if (result_1 == NULL) 
      {
      clnt_perror(clnt, "call failed:");
      }

   clnt_destroy( clnt );
}


/* here is main */
main( int argc, char* argv[] )
{
   char *host;

   /* check correct syntax */
   if( argc < 3 )
   {
     	printf( "usage: %s server_host value ...\n", argv[0]); 
     	exit(1);
   }

   if( argc > MAXAVGSIZE + 2 )
   {
   	printf("Too many input values\n");
    	exit(2);
   }

   /* host name is in first parameter (after program name) */
   host = argv[1];
   averageprog_1( host, argc, argv);
}
