#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include "stdlib.h"
/* run locally on 'server' called by a remote client. */
/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */

input_data * average_1(input_data *input, CLIENT *client) 
  {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  double dp2 = *dp;
  int length = input->input_data.input_data_len; //Should be data length for ease of use
  double values[length];
  u_int x;
  
  // malloc for static input_data
  // A loop for all data from dp that sets the arguements into the array "values"
  for (x=0; x<= length; x++){
	values[x] = *dp;
	dp++;
  }
  // A loop to print out the values array just to visualize them unsorted
  printf("\nThis should be the unsorted list of numbers\n");
  int x3 = 0;
  for(x3 = 0; x3 < length; x3++){
        printf("%e\n", values[x3]);
        }
  printf("\nthis should be the end of the unsorted list\n");
  

  // Basic sort
  int temp, i, j, k;
  for (j = 0; j < length; ++j){
	for (k = j + 1; k < length; ++k){
		if (values[j] > values[k]){
            		temp = values[j];
            		values[j] = values[k];
            		values[k] = temp;
         	}
      	}
  }

  // A loop to print out the values array just to visualize them sorted (and prove)
  printf("\nThis should be the sorted list of numbers\n");
  for(x3 = 0; x3 < length; x3++){
        printf("%e\n", values[x3]);
        }
  printf("\nthis should be the end of the sorted list\n");
  // This line resets the pointer to start at the beginning of DP again
  dp = input->input_data.input_data_val;
  for (x=1; x<length; x++){
	double set = values[x];
	*dp = values[x];
	dp++;	
  }
  return ( input );
  /* iterate until end of number of times (data_len)
  for( i = 1; i <= input->input_data.input_data_len; i++ )
    {
    sum_avg = sum_avg + *dp;   add what ptrs points  to ( '*' gets content ) 
    dp++;
    }
  */
  //sum_avg = sum_avg / input->input_data.input_data_len;
  
  //return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data *average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
